# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49b10bc78bb2c1845c887bd66785f41679def6b8c2cc2e940640ff7e9c5070879af2528c2b7fb44e3c2eee5e03ab04afe92adb9b785bf872b7b04d4b6515512a

test:
  secret_key_base: 0e7b67013511005c3a0c7d8f9fee1efa5bebfa93413b24cb9018b7bd5d94e9fb5eb3cb46fdb9407bb4a519152d544f418f70419813fd90b720927a278b3e8021

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
